language: python

services:
  - docker

before_install:
- docker pull lucasmiranda42/mpip_docker_workshop
- docker run -d -p 127.0.0.1:80:4567 lucasmiranda42/mpip_docker_workshop /bin/sh
- docker ps -a

script:
- coverage run --source . -m pytest
- coverage report -m --include utils.py
- coverage xml -o mpip_workshop_cov.xml